version: '3'

services:
    nginx:
        image: nginx:latest
        ports:
            - "8088:80"
        volumes:
            - ./app:/var/html
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
        container_name: ${PROJECT_NAME}-nginx

    php:
        build: ./docker/php
        volumes:
        - ./app:/var/html
        container_name: ${PROJECT_NAME}-php-fpm
    
    redis:
        image: redis:3.0
        volumes:
            - ./docker/redis/data:/data

    db:
        image: postgres:12.6
        volumes:
            - ./docker/postgres/data:/var/lib/postgresql/data
        ports:
            - 5433:5432
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}